version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_game_db
    restart: always
    # Добавляем эту команду, чтобы изменить кодировку по умолчанию
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: game_database
      MYSQL_USER: game_user
      MYSQL_PASSWORD: your_strong_user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: